---
- hosts: all
  become: true
  tasks:
    - name: Install K3s
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://10.200.0.8:6443 sh -s - agent --token K1029ff3d0517051a44c02261975aa088f515efc2c3f4db373388f64347696bb536::server:91ca79c6fb8a3c641a7c249d2f8afa2e"

    - name: Create .kube directory
      file:
        path: "/home/nadir24950/.kube"
        state: directory
        owner: "nadir24950"
        group: "nadir24950"

    - name: Set KUBECONFIG environment variable
      shell: echo "The value is set"
      environment:
        KUBECONFIG: /home/nadir24950/.kube/config
